/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryproject;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Seviana Pungky B.
 */
public class FormTransaksi extends javax.swing.JFrame {
    LaundryProject konek= new LaundryProject();
    private void namalayanan()
    {
        konek.getkoneksi();
        String sql ="select * from layanan";
        try {
            konek.rs=konek.st.executeQuery(sql);
            while(konek.rs.next()){
                cmbnamalyn.addItem(konek.rs.getString(2));
            }
            konek.rs.last();
            int jumlahdata=konek.rs.getRow();
            konek.rs.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,""+ e);
        }
    }
    private void idtransauto()
    {
        konek.getkoneksi();
        try {
            String sql="select max(right(id_transaksi,7)) as no from transaksi";
            konek.rs=konek.st.executeQuery(sql);
            while(konek.rs.next()){
                
                if(konek.rs.first()==false){
                    txtidtransaksi.setText("T-0000001");
                }
                else{
                    konek.rs.last();
                    int a = konek.rs.getInt(1)+1;
                    String kode1 = String.valueOf(a);
                    int kode_leng=kode1.length();
                    
                    for(int i=0;i<7-kode_leng;i++){
                        kode1="0"+kode1;
                    }
                txtidtransaksi.setText("T-"+kode1);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan ID = "+e);
        }
    }
    
            
        


    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        aktifpertama(true);
        setTombol(true);
        namalayanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btsimpan = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        txtidtransaksi = new javax.swing.JTextField();
        txtnmplg = new javax.swing.JTextField();
        txttglditerima = new javax.swing.JTextField();
        txtberat = new javax.swing.JTextField();
        cmdbacktomenu = new javax.swing.JButton();
        btcetaksblm = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txttgldiambil = new javax.swing.JTextField();
        txtidplg = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        txtidlayanan = new javax.swing.JLabel();
        txtidlyn = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        btdatatransakti = new javax.swing.JButton();
        btsearchplg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcetak = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        btcetaktransid = new javax.swing.JButton();
        lblidtrans = new javax.swing.JLabel();
        cmbnamalyn = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaksi - Camte Laundry Kiloan");

        jLabel1.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI ");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("ID Transaksi");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("ID Pelanggan");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Nama Pelanggan");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Di Terima");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Harga/Kg");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Berat Laundry");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("Nama Layanan");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("TOTAL");

        btsimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btbatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtidtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidtransaksiActionPerformed(evt);
            }
        });

        txtberat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtberatFocusLost(evt);
            }
        });

        cmdbacktomenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdbacktomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/home.png"))); // NOI18N
        cmdbacktomenu.setText("Back To Menu");
        cmdbacktomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbacktomenuActionPerformed(evt);
            }
        });

        btcetaksblm.setText("Cetak Transaksi Sebelumnya");
        btcetaksblm.setEnabled(false);
        btcetaksblm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcetaksblmActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Tanggal Di Ambil");

        txttgldiambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttgldiambilActionPerformed(evt);
            }
        });

        txtidplg.setText("P-");
        txtidplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidplgActionPerformed(evt);
            }
        });

        bttambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        txtidlayanan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtidlayanan.setText("ID Layanan");

        txtidlyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidlynActionPerformed(evt);
            }
        });

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        btdatatransakti.setText("Lihat Data Transaksi");
        btdatatransakti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdatatransaktiActionPerformed(evt);
            }
        });

        btsearchplg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/searchicon-25.png"))); // NOI18N
        btsearchplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchplgActionPerformed(evt);
            }
        });

        txtcetak.setEditable(false);
        txtcetak.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(txtcetak);

        jLabel9.setText("ID = ");
        jLabel9.setEnabled(false);

        btcetaktransid.setText("Cetak Transaksi dengan ID");
        btcetaktransid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcetaktransidActionPerformed(evt);
            }
        });

        lblidtrans.setText("Tidak Ditemukan");
        lblidtrans.setEnabled(false);

        cmbnamalyn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"-"}));
        cmbnamalyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnamalynActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttgldiambil, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txttglditerima)
                            .addComponent(txtnmplg)
                            .addComponent(txtidplg)
                            .addComponent(txtidtransaksi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btsearchplg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btdatatransakti, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtberat, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txtharga))
                                        .addComponent(cmbnamalyn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtidlayanan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidlyn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdbacktomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btcetaktransid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btcetaksblm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)))
                        .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btdatatransakti)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtidtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidlayanan)
                        .addComponent(txtidlyn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btsearchplg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtidplg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel8))
                            .addComponent(cmbnamalyn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtnmplg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttglditerima, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txttgldiambil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(16, 16, 16)
                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btcetaksblm)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btcetaktransid)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdbacktomenu)
                        .addGap(23, 23, 23))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        txtidplg.setText("P-");
        txtnmplg.setText("");
        txttglditerima.setText("");
        txttgldiambil.setText("");
        txtidlyn.setText("");
        cmbnamalyn.setSelectedItem("-");
        txtharga.setText("");
        txtberat.setText("");
        txttotal.setText("");        
    }//GEN-LAST:event_btbatalActionPerformed

    private void cmdbacktomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbacktomenuActionPerformed
        // TODO add your handling code here:
        new FormMenu();
        this.dispose();
    }//GEN-LAST:event_cmdbacktomenuActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txttgldiambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttgldiambilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttgldiambilActionPerformed

    private void txtidplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidplgActionPerformed

    private void txtidlynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidlynActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidlynActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void btdatatransaktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdatatransaktiActionPerformed
        // TODO add your handling code here:
        new DataTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btdatatransaktiActionPerformed

    private void btsearchplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchplgActionPerformed
        // TODO add your handling code here:
        String idplg = txtidplg.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM pelanggan WHERE id_plg like '"+idplg+"'";
            ResultSet rs = statement.executeQuery(sql);
        if (rs.next()){
            aktif(true);
            setTombol(false);
            txtnmplg.setText(rs.getString(2));
            JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        statement.close();
            koneksi.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btsearchplgActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        idtransauto();
        cmbnamalyn.setSelectedItem("-");
        aktif(true);
        setTombol(false);
    }//GEN-LAST:event_bttambahActionPerformed

    private void txtberatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtberatFocusLost
        // TODO add your handling code here:
        float harga= Float.parseFloat(txtharga.getText());
        float berat = Float.parseFloat(txtberat.getText());
        float total=harga*berat;
        txttotal.setText(Float.toString(total));
        
    }//GEN-LAST:event_txtberatFocusLost

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        
        float harga= Float.parseFloat(txtharga.getText());
        float berat=Float.parseFloat(txtberat.getText());
        float total=Float.parseFloat(txttotal.getText());
        String idtransaksi = txtidtransaksi.getText();
        String idplg = txtidplg.getText();
        String nama = txtnmplg.getText();
        String tglterima = txttglditerima.getText();
        String tglambil = txttgldiambil.getText();
        String idlyn = txtidlyn.getText();
        String nmlyn = (String)cmbnamalyn.getSelectedItem();

        
        {
            try{
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
                Statement statement = (Statement) koneksi.createStatement();
                ///String sql="insert into transaksi values('"+idtransaksi+"','"+idplg+"','"+nama+"','"+tglterima+"','"+tglambil+"','"+idlyn+"','"+nmlyn+"')";
                String sql="insert into transaksi values('"+idtransaksi+"','"+idplg+"','"+nama+"','"+tglterima+"','"+tglambil+"','"+idlyn+"','"+nmlyn+"','"+harga+"','"+berat+"','"+total+"')";
                int executeUpdate = statement.executeUpdate(sql);
                statement.close();
                JOptionPane.showMessageDialog(null, "Transaksi berhasil disimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                
                aktif(true);
                idtransauto();
                txtidplg.setText("P-");
                txtnmplg.setText("");
                txttglditerima.setText("");
                txttgldiambil.setText("");
                txtharga.setText("");
                txtberat.setText("");
                txttotal.setText("");
                cmbnamalyn.setSelectedItem("-");
                lblidtrans.setText(idtransaksi);
                btcetaksblm.setEnabled(true);
                lblidtrans.setEnabled(true);
                jLabel9.setEnabled(true);
                
                koneksi.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btcetaksblmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetaksblmActionPerformed
        // TODO add your handling code here:
        String idtrans = lblidtrans.getText();  // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/projectlaundry", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM transaksi WHERE id_transaksi like '"+idtrans+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next()){
                txtcetak.setText(
                        "         \t ***** CAMTE LAUNDRY KILOAN *****"+
                    "\n       \t  Jalan Sadewa IV - 5,  Semarang - 50141"+
                    "\n        \t  Telp .024-3542095 SMS.085640243027"+
                    "\n=========================================================="+
                    "\n\nID Transaksi\t: " + rs.getString(1)+"\tTgl Di Terima : " + rs.getString(4)+
                    "\nNama\t: "+ rs.getString(3)+"\tTgl Di Ambil : " + rs.getString(5)+
                    "\n\n_______________________________________________________"+
                    "\nLayanan\t\tHarga/Kg\tBerat\tTotal\t"+
                    "\n_______________________________________________________"+
                    "\n"+ rs.getString(7)+"\t\t"+ rs.getString(8)+"\t" + rs.getString(9)+"\t" + rs.getString(10)+
                    "\n_______________________________________________________"+
                    "\nTotal Bayar :  Rp." + rs.getString(10)+
                    ",00\n_______________________________________________________\n\n"+
                    "\n=========================================================="+
                    "\nHarap membawa ini jika mengambil laundry."+
                    "\nTerima kasih atas kepercayaan anda."+
                    "\n"+
                    "\n   Hormat Kami,"+
                    "\n"+
                    "\n"+
                    "\n   CamteLaundry"+
                    "\n"
                );
                new FormTransaksi().printComponents(null);
                txtcetak.print();
                txtcetak.setText("");
                lblidtrans.setText("");
            }
            else{
                    JOptionPane.showMessageDialog(null,"Data Sebelumnya tidak ditemukan,mohon Cetak Transaksi lewat ID");
                    txtcetak.setText("");
                    statement.close();
                    koneksi.close();
                }
        }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan"+ex);
        } 
    }//GEN-LAST:event_btcetaksblmActionPerformed

    private void txtidtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtransaksiActionPerformed

    private void btcetaktransidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetaktransidActionPerformed
        // TODO add your handling code here:
        new FormCetakTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcetaktransidActionPerformed

    private void cmbnamalynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnamalynActionPerformed
        // TODO add your handling code here:
        String select= cmbnamalyn.getSelectedItem().toString();
        String sql="select * from layanan where nmlyn ='"+select+"'";

        konek.getkoneksi();
        try {
            konek.rs=konek.st.executeQuery(sql);
            if(konek.rs.next()){
                txtidlyn.setText(konek.rs.getString(1));
                txtharga.setText(konek.rs.getString(3));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,""+ e);

        }
        if(select.equalsIgnoreCase("-")){
            txtidlyn.setText("-");
            txtharga.setText("-");
        }
    }//GEN-LAST:event_cmbnamalynActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btcetaksblm;
    private javax.swing.JButton btcetaktransid;
    private javax.swing.JButton btdatatransakti;
    private javax.swing.JButton btsearchplg;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JComboBox<String> cmbnamalyn;
    private javax.swing.JButton cmdbacktomenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblidtrans;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextPane txtcetak;
    private javax.swing.JTextField txtharga;
    private javax.swing.JLabel txtidlayanan;
    private javax.swing.JTextField txtidlyn;
    private javax.swing.JTextField txtidplg;
    private javax.swing.JTextField txtidtransaksi;
    private javax.swing.JTextField txtnmplg;
    private javax.swing.JTextField txttgldiambil;
    private javax.swing.JTextField txttglditerima;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables


    private void aktif(boolean x) {
      txtidtransaksi.setEditable(!x);
      txtidplg.setEditable(x);
      txtnmplg.setEditable(!x);
      txttglditerima.setEditable(x);
      txttgldiambil.setEditable(x);
      txtidlyn.setEditable(x);
      txtharga.setEditable(!x);
      txtberat.setEditable(x);
      txttotal.setEditable(!x);  
    }
    private void aktifpertama(boolean x) {
      txtidtransaksi.setEditable(!x);
      txtidplg.setEditable(!x);
      txtnmplg.setEditable(!x);
      txttglditerima.setEditable(!x);
      txttgldiambil.setEditable(!x);
      txtidlyn.setEditable(!x);
      txtharga.setEditable(!x);
      txtberat.setEditable(!x);
      txttotal.setEditable(!x);  
    }
    
    private void setTombol(boolean t) {
     bttambah.setEnabled(t);
     btsimpan.setEnabled(!t);
     btbatal.setEnabled(!t);
    }
}
