/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryproject;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seviana Pungky B.
 */
public class FormMasterLayanan extends javax.swing.JFrame {
    private Statement stm;
    private Connection Con;
    private Object con; 
    private ResultSet rs;
    boolean edit = false;
    LaundryProject konek= new LaundryProject();
    /**
     * Creates new form FormMasterLayanan
     */
    private Object[][] dataTable = null; 
    private String[] header =  {"ID Layanan","Nama Layanan","Harga"};
    public FormMasterLayanan() {
        initComponents();
        setLocationRelativeTo(this);
        open_db();
        baca_data();
        aktif(false);
        setTombol(true);
    }
    private void idauto()
    {
        konek.getkoneksi();
        try {
            String sql="select max(right(id_lyn,3)) as no from layanan";
            konek.rs=konek.st.executeQuery(sql);
            while(konek.rs.next()){
                
                if(konek.rs.first()==false){
                    txtidlayanan.setText("L-001");
                }
                else{
                    konek.rs.last();
                    int a = konek.rs.getInt(1)+1;
                    String kode1 = String.valueOf(a);
                    int kode_leng=kode1.length();
                    
                    for(int i=0;i<3-kode_leng;i++){
                        kode1="0"+kode1;
                    }
                txtidlayanan.setText("L-"+kode1);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan ID = "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidlayanan = new javax.swing.JTextField();
        txtnmlayanan = new javax.swing.JTextField();
        txthrglayanan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tlayanan = new javax.swing.JTable();
        btbatal = new javax.swing.JButton();
        btmenu = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Layanan - Camte Laundry Kiloan");

        jLabel1.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASTER LAYANAN");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("ID Layanan");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Nama Layanan");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Harga/Kg");

        txtidlayanan.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtidlayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidlayananActionPerformed(evt);
            }
        });

        txtnmlayanan.setMargin(new java.awt.Insets(4, 4, 4, 4));

        txthrglayanan.setMargin(new java.awt.Insets(4, 4, 4, 4));

        tlayanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tlayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Layanan", "Nama Layanan", "Harga/KG"
            }
        ));
        tlayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlayananMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tlayanan);

        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        btmenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/home.png"))); // NOI18N
        btmenu.setText("Back To Menu");
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });

        btsimpan.setText("Simpan");
        btsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsimpanMouseClicked(evt);
            }
        });
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtidlayanan, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(txtnmlayanan)
                    .addComponent(txthrglayanan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btmenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidlayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnmlayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthrglayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btubah)
                    .addComponent(bthapus)
                    .addComponent(btbatal)
                    .addComponent(bttambah)
                    .addComponent(btsimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btmenu)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidlayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidlayananActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtidlayananActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
        // TODO add your handling code here:
        new FormMenu();
        this.dispose();
    }//GEN-LAST:event_btmenuActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        aktif(true);
        setTombol(true);
        txtidlayanan.setText("");
        txtnmlayanan.setText("");
        txthrglayanan.setText("");
        
    }//GEN-LAST:event_btbatalActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        // TODO add your handling code here:
        edit=true;
        aktif(true);
        setTombol(false);
        txtidlayanan.setEditable(false); 
        
    }//GEN-LAST:event_btubahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        String idlayanan = txtidlayanan.getText();
            try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/projectlaundry","root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="delete from layanan where id_lyn='"+idlayanan+"'";
            statement.executeUpdate(sql);
            baca_data(); 
            statement.close();
            txtidlayanan.setText("");
            txtnmlayanan.setText("");
            txthrglayanan.setText("");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
            koneksi.close();
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) { JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            } 
    }//GEN-LAST:event_bthapusActionPerformed

    private void tlayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlayananMouseClicked
        // TODO add your handling code here:
        setField();
    }//GEN-LAST:event_tlayananMouseClicked

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        idauto();
        txtidlayanan.setEditable(false);
        aktif(true);
        setTombol(false);
    }//GEN-LAST:event_bttambahActionPerformed

    private void btsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsimpanMouseClicked
        // TODO add your handling code here:
        String idlayanan = txtidlayanan.getText();
        String nmlayanan = txtnmlayanan.getText();
        int harga=Integer.parseInt(txthrglayanan.getText()); 
        {
            try{
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
                Statement statement = (Statement) koneksi.createStatement();
                if (edit==true){ 
                    statement.executeUpdate("update layanan set nmlyn='"+nmlayanan+"',hrglyn='"+harga+"' where id_lyn='"+idlayanan+"'"); 
                }
               else { 
                   statement.executeUpdate("insert into layanan values('"+idlayanan+"','"+nmlayanan+"','"+harga+"')"); 
               }
                
                tlayanan.setModel(new DefaultTableModel(dataTable,header)); 
                baca_data(); 
                aktif(false); 
                setTombol(true); 
                
                statement.close();
                JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                
                aktif(true);
                txtidlayanan.setText("");
                txtnmlayanan.setText("");
                txthrglayanan.setText("");
                koneksi.close();
            }
            catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btsimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasterLayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasterLayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasterLayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasterLayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMasterLayanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btmenu;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tlayanan;
    private javax.swing.JTextField txthrglayanan;
    private javax.swing.JTextField txtidlayanan;
    private javax.swing.JTextField txtnmlayanan;
    // End of variables declaration//GEN-END:variables
 private void setField() { 
    int row=tlayanan.getSelectedRow(); 
    txtidlayanan.setText((String)tlayanan.getValueAt(row,0)); 
    txtnmlayanan.setText((String)tlayanan.getValueAt(row,1)); 
    txthrglayanan.setText((String)tlayanan.getValueAt(row,2)); 

} 
    private void aktif(boolean x) {
      txtidlayanan.setEditable(x);
      txtnmlayanan.setEditable(x);
      txthrglayanan.setEditable(x);
    }
     private void setTombol(boolean t) {
     bttambah.setEnabled(t);
     btsimpan.setEnabled(!t);
     bthapus.setEnabled(t);
     btubah.setEnabled(t);
     btbatal.setEnabled(!t);
    }
    private void open_db() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/projectlaundry","root","");
            stm = (Statement) Con.createStatement();

        }catch (ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,"Koneksi gagal");
            System.out.println(e.getMessage());
        }
    }


    private void baca_data() { 
        try{ 
            stm = (Statement) Con.createStatement(); 
            rs = stm.executeQuery("select * from layanan"); 
            ResultSetMetaData meta = rs.getMetaData(); 
            int col = meta.getColumnCount();       
            int baris = 0; 
            while(rs.next()) { 
                baris = rs.getRow(); 
            } 
            dataTable = new Object[baris][col]; 
            int x = 0; 
            rs.beforeFirst(); 
            while(rs.next()) { 
                dataTable[x][0] = rs.getString("id_lyn"); 
                dataTable[x][1] = rs.getString("nmlyn"); 
                dataTable[x][2] = rs.getString("hrglyn"); 
                x++; 
            } 
            tlayanan.setModel(new DefaultTableModel(dataTable,header));         
        } 
        catch(SQLException e) { 
            JOptionPane.showMessageDialog(null, e); 
        } 
    } 

}
