/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryproject;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;


/**
 *
 * @author Seviana Pungky B.
 */
public class FormStatus extends javax.swing.JFrame {
    LaundryProject konek= new LaundryProject();
    private Statement stm;
    private Connection Con;
    private Object con; 
    private ResultSet rs;
    

    /**
     * Creates new form FormStatus
     */
    public FormStatus() {
        initComponents();        
        setTombol(true);
        aktif(true);        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btsearch = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnmplg = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        btsimpan = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btmenu = new javax.swing.JButton();
        txtidtransaksi = new javax.swing.JTextField();
        txtidplg = new javax.swing.JTextField();
        btsearchtrans = new javax.swing.JButton();
        btdatastatus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txttgljd = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btsearchno = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/searchicon-25.png"))); // NOI18N
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status - Camte Laundry Kiloan");

        jLabel1.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATUS LAUNDRY");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setText("ID Transaksi");

        jLabel3.setText("ID Pelanggan");

        jLabel4.setText("Nama Pelanggan");

        jLabel5.setText("Status");

        txtnmplg.setEditable(false);
        txtnmplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmplgActionPerformed(evt);
            }
        });

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Diambil", "Sudah Diambil" }));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btmenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/home.png"))); // NOI18N
        btmenu.setText("Back To Menu");
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });

        txtidtransaksi.setText("T-");
        txtidtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidtransaksiActionPerformed(evt);
            }
        });

        txtidplg.setEditable(false);
        txtidplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidplgActionPerformed(evt);
            }
        });

        btsearchtrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/searchicon-25.png"))); // NOI18N
        btsearchtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchtransActionPerformed(evt);
            }
        });

        btdatastatus.setText("Lihat Data Status");
        btdatastatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdatastatusActionPerformed(evt);
            }
        });

        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Jadi");

        txttgljd.setEditable(false);
        txttgljd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttgljdActionPerformed(evt);
            }
        });

        txtno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnoFocusLost(evt);
            }
        });
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Status");

        btsearchno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryproject/images/searchicon-25.png"))); // NOI18N
        btsearchno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btmenu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btubah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btdatastatus)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtno)
                    .addComponent(txttgljd)
                    .addComponent(txtnmplg, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidtransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidplg)
                    .addComponent(cbstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsearchno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsearchtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btdatastatus)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(btsearchno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidplg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnmplg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttgljd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btsearchtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbatal)
                    .addComponent(bthapus)
                    .addComponent(btsimpan)
                    .addComponent(btubah)
                    .addComponent(bttambah))
                .addGap(20, 20, 20)
                .addComponent(btmenu)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        aktif(true);
        setTombol(true);
        txtno.setText("");
        txtidtransaksi.setText("T-");
        txtidplg.setText("");
        txtnmplg.setText("");
        txttgljd.setText("");
        cbstatus.setSelectedItem(0);
        
        
    }//GEN-LAST:event_btbatalActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
        // TODO add your handling code here:
        new FormMenu();
        this.dispose();
    }//GEN-LAST:event_btmenuActionPerformed

    private void txtnmplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmplgActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsearchActionPerformed

    private void btsearchtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchtransActionPerformed
        // TODO add your handling code here:
        String idtrans = txtidtransaksi.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM transaksi WHERE id_transaksi like '"+idtrans+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next()){
            aktif(true);
            bttambah.setEnabled(false);
            btsimpan.setEnabled(true);
            bthapus.setEnabled(false);
            btubah.setEnabled(false);
            btbatal.setEnabled(true);
            txtidplg.setText(rs.getString(2));
            txtnmplg.setText(rs.getString(3));
            txttgljd.setText(rs.getString(5));
            JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        statement.close();
            koneksi.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btsearchtransActionPerformed

    private void txtidtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtransaksiActionPerformed

    private void txtidplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidplgActionPerformed

    private void btdatastatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdatastatusActionPerformed
        // TODO add your handling code here:
        new DataStatus().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btdatastatusActionPerformed

    private void txttgljdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttgljdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttgljdActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        aktif(true);
        bttambah.setEnabled(false);
        btsimpan.setEnabled(true);
        bthapus.setEnabled(false);
        btubah.setEnabled(false);
        btbatal.setEnabled(true);
        idauto();
    }//GEN-LAST:event_bttambahActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        String no = txtno.getText();
        String idtransaksi = txtidtransaksi.getText();
        String idplg = txtidplg.getText();
        String nama = txtnmplg.getText();
        String tgljd = txttgljd.getText();
        String sts = (String) cbstatus.getSelectedItem();
        {
            try{
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection koneksi = (Connection) DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
                Statement statement = (Statement) koneksi.createStatement();
                String sql="insert into status values('"+no+"','"+idtransaksi+"','"+idplg+"','"+nama+"','"+tgljd+"','"+sts+"')";
                int executeUpdate = statement.executeUpdate(sql);
                statement.close();
                JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                aktif(true);
                idauto();
                txtidtransaksi.setText("T-");
                txtidplg.setText("");
                txtnmplg.setText("");
                txttgljd.setText("");
                cbstatus.setSelectedItem(0);
                koneksi.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoFocusLost

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        // TODO add your handling code here:
        String no = txtno.getText();
        String idtransaksi = txtidtransaksi.getText();
        String idplg = txtidplg.getText();
        String nama = txtnmplg.getText();
        String tgljd = txttgljd.getText();
        String sts = (String) cbstatus.getSelectedItem();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="UPDATE status SET id_status='"+no+"',id_transaksi='"+idtransaksi+"',id_plg='"+idplg+"',namaplg='"+nama+"',tgljd='"+tgljd+"' WHERE id_status LIKE '"+no+"'";
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah","Informasi",JOptionPane.INFORMATION_MESSAGE);
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btubahActionPerformed

    private void btsearchnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchnoActionPerformed
        // TODO add your handling code here:
        String no = txtno.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM status WHERE id_status like '"+no+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next()){
            aktif(true);
            bttambah.setEnabled(false);
            btsimpan.setEnabled(false);
            bthapus.setEnabled(true);
            btubah.setEnabled(true);
            btbatal.setEnabled(true);
            txtidtransaksi.setText(rs.getString(2));
            txtidplg.setText(rs.getString(3));
            txtnmplg.setText(rs.getString(4));
            txttgljd.setText(rs.getString(5));
            cbstatus.setSelectedItem(0);
            
            JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        statement.close();
            koneksi.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btsearchnoActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        String no = txtno.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/projectlaundry", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="DELETE FROM status WHERE id_status LIKE '"+no+"'";
            statement.executeUpdate(sql);
            statement.close();
            txtno.setText("");
            txtidtransaksi.setText("T-");
            txtidplg.setText("");
            txtnmplg.setText("");
            txttgljd.setText("");
            cbstatus.setSelectedItem(0);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) { JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bthapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btdatastatus;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btmenu;
    private javax.swing.JButton btsearch;
    private javax.swing.JButton btsearchno;
    private javax.swing.JButton btsearchtrans;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtidplg;
    private javax.swing.JTextField txtidtransaksi;
    private javax.swing.JTextField txtnmplg;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txttgljd;
    // End of variables declaration//GEN-END:variables
    private void idauto()
    {
        konek.getkoneksi();
        try {
            String sql="select max(right(id_status,7)) as no from status";
            konek.rs=konek.st.executeQuery(sql);
            while(konek.rs.next()){
                
                if(konek.rs.first()==false){
                    txtno.setText("S-0000001");
                }
                else{
                    konek.rs.last();
                    int a = konek.rs.getInt(1)+1;
                    String kode1 = String.valueOf(a);
                    int kode_leng=kode1.length();
                    
                    for(int i=0;i<7-kode_leng;i++){
                        kode1="0"+kode1;
                    }
                txtno.setText("S-"+kode1);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan ID = "+e);
        }
    }
    
    private void setTombol(boolean t) {
     bttambah.setEnabled(t);
     btsimpan.setEnabled(!t);
     bthapus.setEnabled(!t);
     btubah.setEnabled(!t);
     btbatal.setEnabled(!t);
    }
    private void aktif(boolean x) {
      txtno.requestFocus(x);
      txtidtransaksi.setEditable(x);
    }
}
